# Generated by Django 3.0.8 on 2020-07-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200717_0443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
